os:
  - linux
dist: trusty

language: c

install:
  - |
      wget https://nim-lang.org/download/nim-0.18.0.tar.xz
      tar -xf nim-0.18.0.tar.xz
      cd nim-0.18.0
      sh build.sh
      cd ..
before_script:
  - set -e
  - set -x
  - export PATH=`pwd`/nim-0.18.0/bin:$PATH

script:
  - cd src
  - nim c -r vulkan
  - cd ..
  - ./src/vulkan install -y
